
[build]
  command = "vite build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/pwa-test/*"
  to = "/pwa-test/index.html"
  status = 200
