name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Build step with enhanced error handling
      - name: Build
        run: |
          echo "Starting build process..."
          npm run build || (echo "Build failed" && exit 1)
        env:
          VITE_BASE_URL: '/${{ github.event.repository.name }}'

      # Debug: Show directory structure and file contents
      - name: Debug build output
        run: |
          echo "Workspace directory: ${{ github.workspace }}"
          echo "Current directory contents:"
          ls -la
          echo "\nBuild directory contents (dist/public):"
          ls -la dist/public/
          echo "\nFull directory tree:"
          find ${{ github.workspace }} -type f
          echo "\nVerifying index.html exists:"
          cat dist/public/index.html || (echo "index.html not found!" && exit 1)

      # Upload artifact with explicit name and path
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ github.workspace }}/dist/public
          retention-days: 1

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2